customhost = "employee.crhpyun5diaf.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "amos-mingann-assignment"
customregion = "us-east-1b"
